[build-system]
requires = [
    "setuptools>=59",
    "setuptools_scm[toml]>=6.4",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["lovely"]
addopts = "--doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE"
